# replace  192.168.1.15 with the fixed IP of your NFS server
# replace  /home/pi/nfs/k8sdata with the path to your NFS server folder

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data
    server: 192.168.50.133
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: pvc-grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: pvc-grafana
#  labels:
#    app: grafana
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 50Mi
